"""feat: agregando tabla tipos_descuento

Revision ID: 0873f12310c1
Revises: 571085e85cec
Create Date: 2026-04-26 22:03:38.078788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0873f12310c1'
down_revision: Union[str, Sequence[str], None] = '571085e85cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_descuento',
    sa.Column('id_tipo_descuento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('requiere_documento', sa.Boolean(), nullable=False),
    sa.Column('id_requisito_extra', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_requisito_extra'], ['requisito.id_requisito'], ),
    sa.PrimaryKeyConstraint('id_tipo_descuento'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipos_descuento_id_tipo_descuento'), 'tipos_descuento', ['id_tipo_descuento'], unique=False)
    op.add_column('detalle_programa_alumno', sa.Column('id_tipo_descuento', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detalle_programa_alumno', 'tipos_descuento', ['id_tipo_descuento'], ['id_tipo_descuento'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detalle_programa_alumno', type_='foreignkey')
    op.drop_column('detalle_programa_alumno', 'id_tipo_descuento')
    op.drop_index(op.f('ix_tipos_descuento_id_tipo_descuento'), table_name='tipos_descuento')
    op.drop_table('tipos_descuento')
    # ### end Alembic commands ###
