"""feat: agregar unique constraint id_programa+version en programas_version

Revision ID: 1256ccea74d8
Revises: 7b4b157a0c25
Create Date: 2026-05-19 14:53:53.380379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1256ccea74d8'
down_revision: Union[str, Sequence[str], None] = '7b4b157a0c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_programa_version', 'programas_version', ['id_programa', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_programa_version', 'programas_version', type_='unique')
    # ### end Alembic commands ###
