"""feat: agregando tabla de control de documentacion

Revision ID: 9263e1c455a2
Revises: b84bbaf6e7f1
Create Date: 2026-04-25 11:33:31.393463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9263e1c455a2'
down_revision: Union[str, Sequence[str], None] = 'b84bbaf6e7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_documentacion',
    sa.Column('id_control_documentacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_detalle_programa_alumno', sa.Integer(), nullable=False),
    sa.Column('id_requisito', sa.Integer(), nullable=False),
    sa.Column('entregado', sa.Boolean(), nullable=False),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_detalle_programa_alumno'], ['detalle_programa_alumno.id_detalle_programa_alumno'], ),
    sa.ForeignKeyConstraint(['id_requisito'], ['requisito.id_requisito'], ),
    sa.PrimaryKeyConstraint('id_control_documentacion')
    )
    op.create_index(op.f('ix_control_documentacion_id_control_documentacion'), 'control_documentacion', ['id_control_documentacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_control_documentacion_id_control_documentacion'), table_name='control_documentacion')
    op.drop_table('control_documentacion')
    # ### end Alembic commands ###
